In [1]:

from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:

voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2764, 365, 2258, 9555], [2764, 365, 2258, 8274], [2764, 5089, 2258, 9399], [6887, 4646, 5342, 2141, 3421], [6887, 4646, 5342, 2141, 473], [831, 2764, 9237, 2258, 5044], [6774, 627, 3287, 2141]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2764  365 2258 9555]
 [   0    0    0    0 2764  365 2258 8274]
 [   0    0    0    0 2764 5089 2258 9399]
 [   0    0    0 6887 4646 5342 2141 3421]
 [   0    0    0 6887 4646 5342 2141  473]
 [   0    0    0  831 2764 9237 2258 5044]
 [   0    0    0    0 6774  627 3287 2141]]


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]
  [ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]
  [ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]
  [ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]
  [ 0.0233246   0.01284141 -0.0496002  -0.01598377 -0.04683396
    0.0253536  -0.02548846 -0.02006301  0.03445477 -0.04010203]
  [-0.02797616 -0.02184573 -0.00291377 -0.03438094 -0.01953979
   -0.0137511   0.01360113  0.04526872 -0.03285779  0.02624878]
  [ 0.04997689 -0.00549998  0.01922247  0.03833392  0.03649826
    0.03558953  0.04922021  0.01363555  0.03747643  0.04337153]
  [-0.02502993  0.04463922  0.01270059  0.02427307 -0.0413955
   -0.04857037  0.00449176 -0.01361736  0.04165841 -0

In [13]:

embedded_docs[0]

array([   0,    0,    0,    0, 2764,  365, 2258, 9555])

In [15]:
print(model.predict(embedded_docs[0]))

[[[ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]]

 [[ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]]

 [[ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]]

 [[ 0.01282425 -0.03755627 -0.02505985  0.02887631  0.0138654
   -0.03305351  0.01160501  0.03449384  0.00931816  0.0084196 ]]

 [[ 0.0233246   0.01284141 -0.0496002  -0.01598377 -0.04683396
    0.0253536  -0.02548846 -0.02006301  0.03445477 -0.04010203]]

 [[-0.02797616 -0.02184573 -0.00291377 -0.03438094 -0.01953979
   -0.0137511   0.01360113  0.04526872 -0.03285779  0.02624878]]

 [[ 0.04997689 -0.00549998  0.01922247  0.03833392  0.03649826
    0.03558953  0.04922021  0.01363555  0.03747643  0.04337153]]

 [[-0.02502993  0.04463922  0.01270059  0.02427307 -0.0413955
   -0.04857037  0.00449176 -0.01361736 